env:
  WORKDIR: "/tmp"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'Adalat222'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G
  Init_script:
    - repo init -u https://github.com/Project-Elixir/manifest -b Tiramisu
  Download_script:
    - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  Setup_Config_script:
    - git clone --depth=1 https://github.com/Molyuu/neko_kernel_xiaomi_gauguin kernel/xiaomi/gauguin
    - git clone --depth=1 https://github.com/yusufnoor786/device-xiaomi-gauguin device/xiaomi/gauguin
    - git clone --depth=1 https://github.com/chitangUI/vendor_xiaomi_gauguin vendor/xiaomi/gauguin
    -  . build/envsetup.sh
    - lunch aosp_$device-userdebug
  Build_Code_script:
    - mka bacon -j8

