env:
  WORKDIR: "/tmp"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'Adalat222'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G
  Init_script:
    - repo init -u https://github.com/Evolution-X/manifest -b tiramisu
  Download_script:
    - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  Setup_Config_script:
    - git clone --depth=1 https://github.com/LineageOS/android_kernel_xiaomi_gauguin kernel/xiaomi/gauguin
    - git clone --depth=1 https://github.com/iitzrohan/device_xiaomi_gauguin device/xiaomi/gauguin
    -  . build/envsetup.sh
    - lunch evolution_$device-userdebug
  Build_Code_script:
    - mka evolution

